# Generated by Django 2.2.8 on 2019-12-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0003_auto_20191205_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest', models.DecimalField(decimal_places=2, max_digits=6)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=6)),
                ('abdomen', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hip', models.DecimalField(decimal_places=2, max_digits=6)),
                ('thigh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('proximal_thigh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calf', models.DecimalField(decimal_places=2, max_digits=6)),
                ('relaxed_arm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('arm_contracted', models.DecimalField(decimal_places=2, max_digits=6)),
                ('forearm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fist', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SkinFolds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biceps', models.DecimalField(decimal_places=2, max_digits=6)),
                ('triceps', models.DecimalField(decimal_places=2, max_digits=6)),
                ('abdominal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('axillary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('suprailiac', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subscapular', models.DecimalField(decimal_places=2, max_digits=6)),
                ('chest', models.DecimalField(decimal_places=2, max_digits=6)),
                ('thigh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('medial_calf', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('body_fat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('measures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='appraisal.Measures')),
                ('skin_folds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='appraisal.SkinFolds')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='student.Student')),
            ],
        ),
    ]
