# Generated by Django 2.2.8 on 2019-12-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
