# Generated by Django 2.2.8 on 2019-12-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20191204_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appraisal',
        ),
        migrations.DeleteModel(
            name='Measures',
        ),
        migrations.DeleteModel(
            name='SkinFolds',
        ),
    ]
